import { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Language = "en" | "fr" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.map": "Map",
    "nav.report": "Report",
    "nav.signin": "Sign in",
    "nav.signout": "Sign out",
    "nav.getstarted": "Get Started",
    "nav.profile": "Profile",
    
    // Landing
    "landing.hero.title": "Safety Platform for Women in Tunisia",
    "landing.hero.subtitle": "Report street harassment, visualize danger zones, walk safely with community support, and access verified safe spaces.",
    "landing.hero.badge": "Safety Platform for Women in Tunisia",
    "landing.hero.map": "Open Safety Map",
    "landing.hero.getstarted": "Get Started",
    
    // Movement
    "landing.movement.title": "Building a Safer Tunisia",
    "landing.movement.description": "EnaZeda represents a collective stand against sexual harassment in Tunisia. We're building a community-driven platform that empowers women to report incidents, share experiences, and create safer public spaces together.",
    "landing.movement.data": "Real-Time Data",
    "landing.movement.data.desc": "Visualize harassment patterns across Tunisian cities with our interactive safety heatmap.",
    "landing.movement.community": "Community Support",
    "landing.movement.community.desc": "Connect with trusted contacts and verified volunteers who can help you walk safely.",
    "landing.movement.spaces": "Verified Safe Spaces",
    "landing.movement.spaces.desc": "Find cafes, pharmacies, and public buildings verified by the community as safe havens.",
    "landing.movement.secure": "Secure & Trusted",
    "landing.movement.secure.desc": "Real accounts, trusted reporting, and secure infrastructure for your safety and privacy.",
    
    // How it works
    "landing.howitworks.title": "How It Works",
    "landing.howitworks.subtitle": "A mobile-first platform optimized for low data usage, fast performance, and accessibility.",
    "landing.howitworks.report": "Report Incidents",
    "landing.howitworks.report.desc": "Anonymously report street harassment incidents. Your reports help build a comprehensive safety map for everyone.",
    "landing.howitworks.visualize": "Visualize Danger Zones",
    "landing.howitworks.visualize.desc": "See real-time heatmaps of reported incidents. Plan safer routes and avoid high-risk areas.",
    "landing.howitworks.walk": "Walk Safely",
    "landing.howitworks.walk.desc": "Share your live location with trusted contacts. One-tap panic button for emergencies.",
    
    // Stats
    "landing.stats.anonymous": "Anonymous Reporting",
    "landing.stats.support": "Community Support",
    "landing.stats.verified": "Verified Safe Spaces",
    
    // CTA
    "landing.cta.title": "Join the Movement",
    "landing.cta.description": "Every report helps. Every safe walk matters. Together, we're building a safer Tunisia for all women.",
    "landing.cta.create": "Create Account",
    "landing.cta.explore": "Explore Map",
    
    // Footer
    "footer.tagline": "Safety platform for women in Tunisia • Building a scalable public safety network",
    "footer.about": "About",
    "footer.contact": "Contact",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.resources": "Resources",
    "footer.safetymap": "Safety Map",
    "footer.report": "Report Incident",
    "footer.safespaces": "Safe Spaces",
    
    // About
    "about.title": "About EnaZeda",
    "about.mission": "Our Mission",
    "about.mission.desc": "EnaZeda is a safety platform designed specifically for women in Tunisia. We provide tools to report street harassment, visualize danger zones, walk safely with community support, and access verified safe spaces. Our mission is to build a scalable public safety network that empowers women and creates safer communities.",
    "about.movement": "The Movement",
    "about.movement.desc": "EnaZeda is a safety platform empowering women in Tunisia. We believe that every woman has the right to move freely and safely in public spaces. Through community-driven reporting and verified data, we're creating a comprehensive safety network that helps women make informed decisions about their routes and activities.",
    "about.how": "How We Work",
    "about.anonymous": "Anonymous Reporting",
    "about.anonymous.desc": "Users can anonymously report incidents of street harassment. All reports are verified and contribute to our safety heatmap, helping others avoid high-risk areas.",
    "about.verification": "Community Verification",
    "about.verification.desc": "Safe spaces are verified by the community. Cafes, pharmacies, and public buildings are marked as safe havens where women can seek help if needed.",
    "about.support": "Real-Time Support",
    "about.support.desc": "The Walk With Me feature allows users to share their live location with trusted contacts and access emergency support through a one-tap panic button.",
    "about.privacy": "Privacy & Security",
    "about.privacy.desc": "We take privacy and security seriously. All reports are anonymous, and user data is protected with secure infrastructure. We use real accounts and trusted reporting to maintain the integrity of our platform while protecting user privacy.",
    "about.involved": "Get Involved",
    "about.involved.desc": "Join us in building a safer Tunisia. Every report helps, every safe walk matters. Together, we can create change.",
    "about.create": "Create Account",
    
    // Contact
    "contact.title": "Contact Us",
    "contact.subtitle": "Have questions or feedback? We'd love to hear from you.",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.subject": "Subject",
    "contact.message": "Message",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.other": "Other Ways to Reach Us",
    "contact.email.label": "Email:",
    "contact.support.label": "Support:",
    
    // Privacy
    "privacy.title": "Privacy Policy",
    "privacy.lastupdated": "Last updated:",
    "privacy.intro": "Introduction",
    "privacy.intro.desc": "EnaZeda (\"we\", \"our\", or \"us\") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our safety platform.",
    "privacy.collect": "Information We Collect",
    "privacy.account": "Account Information",
    "privacy.account.desc": "When you create an account, we collect your phone number for authentication purposes. This information is stored securely and used only for account management.",
    "privacy.reports": "Incident Reports",
    "privacy.reports.desc": "Reports submitted through our platform are anonymous. We collect location data, incident type, and optional descriptions to build our safety heatmap. No personally identifiable information is associated with reports.",
    "privacy.location": "Location Data",
    "privacy.location.desc": "Location data is collected only when you actively use features like \"Walk With Me\" or when submitting reports. This data is used solely for safety purposes and is not shared with third parties.",
    "privacy.use": "How We Use Your Information",
    "privacy.use.list1": "To provide and maintain our safety platform",
    "privacy.use.list2": "To process and display anonymous incident reports on our safety map",
    "privacy.use.list3": "To enable location sharing features when requested",
    "privacy.use.list4": "To improve our services and user experience",
    "privacy.use.list5": "To communicate with you about your account or our services",
    "privacy.security": "Data Security",
    "privacy.security.desc": "We implement appropriate technical and organizational measures to protect your personal information. All data is encrypted in transit and at rest. We use secure infrastructure and follow industry best practices to safeguard your information.",
    "privacy.rights": "Your Rights",
    "privacy.rights.desc": "You have the right to:",
    "privacy.rights.list1": "Access your personal information",
    "privacy.rights.list2": "Request correction of inaccurate data",
    "privacy.rights.list3": "Request deletion of your account and data",
    "privacy.rights.list4": "Opt out of location tracking when not using safety features",
    "privacy.contact": "Contact Us",
    "privacy.contact.desc": "If you have questions about this Privacy Policy, please contact us at privacy@enazeda.tn",
    
    // Terms
    "terms.title": "Terms of Service",
    "terms.lastupdated": "Last updated:",
    "terms.agreement": "Agreement to Terms",
    "terms.agreement.desc": "By accessing or using EnaZeda, you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access the service.",
    "terms.use": "Use of Service",
    "terms.eligibility": "Eligibility",
    "terms.eligibility.desc": "You must be at least 18 years old to use EnaZeda. By using the service, you represent that you meet this requirement.",
    "terms.responsibility": "Account Responsibility",
    "terms.responsibility.desc": "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.",
    "terms.acceptable": "Acceptable Use",
    "terms.acceptable.desc": "You agree to use EnaZeda only for lawful purposes and in accordance with these Terms. You agree not to submit false reports, abuse the reporting system, or interfere with the platform's functionality.",
    "terms.reports": "Incident Reports",
    "terms.reports.desc": "When submitting incident reports, you agree that:",
    "terms.reports.list1": "Reports are submitted in good faith and based on actual experiences",
    "terms.reports.list2": "You will not submit false, misleading, or malicious reports",
    "terms.reports.list3": "All reports are anonymous and cannot be traced back to you",
    "terms.reports.list4": "Reports may be reviewed and verified by our team",
    "terms.liability": "Limitation of Liability",
    "terms.liability.desc": "EnaZeda is provided \"as is\" without warranties of any kind. We do not guarantee the accuracy, completeness, or reliability of information on the platform. We are not liable for any harm that may result from using or relying on information provided through our service.",
    "terms.modifications": "Modifications",
    "terms.modifications.desc": "We reserve the right to modify these Terms at any time. Continued use of the service after changes constitutes acceptance of the new Terms.",
    "terms.contact": "Contact",
    "terms.contact.desc": "For questions about these Terms, contact us at legal@enazeda.tn",
    
    // Auth
    "auth.welcome": "Welcome to EnaZeda",
    "auth.subtitle": "Sign in to access the safety platform",
    "auth.email": "Email",
    "auth.email.placeholder": "your@email.com",
    "auth.password": "Password",
    "auth.password.placeholder": "Enter your password",
    "auth.signin": "Sign In",
    "auth.signup": "Sign Up",
    "auth.or": "Or",
    "auth.google": "Continue with Google",
    "auth.phone": "Phone Number",
    "auth.phone.option": "Use phone instead",
    "auth.continue": "Continue",
    "auth.sending": "Sending code...",
    "auth.verify": "Verify your number",
    "auth.sent": "We sent a code to",
    "auth.verifybutton": "Verify & Sign In",
    "auth.verifying": "Verifying...",
    "auth.change": "Change number",
    "auth.switch": "Switch to email",
    "auth.agree": "By continuing, you agree to our terms of service and privacy policy.",
    "auth.noaccount": "Don't have an account?",
    "auth.haveaccount": "Already have an account?",
    "auth.forgot": "Forgot password?",
    
    // Profile
    "profile.title": "Account",
    "profile.notsigned": "Not signed in",
    "profile.signin": "Sign in",
    "profile.trust": "Trust score",
    "profile.trust.desc": "Build trust by contributing to the community.",
    "profile.contacts": "Emergency contacts",
    "profile.contacts.desc": "Manage trusted contacts",
    "profile.guardians": "Trusted guardians",
    "profile.guardians.desc": "People who can join walks",
    "profile.history": "History",
    "profile.history.desc": "Past reports and walks",
    "profile.notifications": "Notifications",
    "profile.notifications.desc": "Alert preferences",
    "profile.language": "Language",
    "profile.language.desc": "English",
    "profile.privacy": "Privacy",
    "profile.privacy.desc": "Control your data",
    "profile.signout": "Sign out",
    
    // Emergency Contacts
    "contacts.add": "Add contact",
    "contacts.save": "Save",
    "contacts.update": "Update",
    "contacts.cancel": "Cancel",
    "contacts.form.name": "Name",
    "contacts.form.name.placeholder": "Contact name",
    "contacts.form.phone": "Phone",
    "contacts.form.phone.placeholder": "+216 XX XXX XXX",
    "contacts.error.title": "Missing information",
    "contacts.error.desc": "Please fill in all required fields",
    "contacts.added.title": "Contact added",
    "contacts.added.desc": "Emergency contact has been saved",
    "contacts.updated.title": "Contact updated",
    "contacts.updated.desc": "Emergency contact has been updated",
    "contacts.deleted.title": "Contact deleted",
    "contacts.deleted.desc": "Emergency contact has been removed",
    "contacts.empty.title": "No emergency contacts",
    "contacts.empty.desc": "Add trusted contacts for emergency situations",
    
    // Trusted Guardians
    "guardians.add": "Add guardian",
    "guardians.save": "Save",
    "guardians.update": "Update",
    "guardians.cancel": "Cancel",
    "guardians.form.name": "Name",
    "guardians.form.name.placeholder": "Guardian name",
    "guardians.form.phone": "Phone",
    "guardians.form.phone.placeholder": "+216 XX XXX XXX",
    "guardians.form.email": "Email",
    "guardians.form.email.optional": "Optional",
    "guardians.form.email.placeholder": "guardian@email.com",
    "guardians.error.title": "Missing information",
    "guardians.error.desc": "Please fill in name and phone",
    "guardians.added.title": "Guardian added",
    "guardians.added.desc": "Trusted guardian has been saved",
    "guardians.updated.title": "Guardian updated",
    "guardians.updated.desc": "Trusted guardian has been updated",
    "guardians.deleted.title": "Guardian deleted",
    "guardians.deleted.desc": "Trusted guardian has been removed",
    "guardians.empty.title": "No trusted guardians",
    "guardians.empty.desc": "Add people who can join your walks",
    
    // History
    "history.filter.all": "All",
    "history.filter.reports": "Reports",
    "history.filter.walks": "Walks",
    "history.empty.title": "No history",
    "history.empty.desc": "Your reports and walks will appear here",
    
    // Notifications
    "notifications.reports.title": "Report notifications",
    "notifications.reports.desc": "Get notified about nearby incidents",
    "notifications.walks.title": "Walk notifications",
    "notifications.walks.desc": "Alerts during walk sessions",
    "notifications.safeSpaces.title": "Safe spaces",
    "notifications.safeSpaces.desc": "Updates about verified safe locations",
    "notifications.emergency.title": "Emergency alerts",
    "notifications.emergency.desc": "Critical safety notifications",
    "notifications.community.title": "Community updates",
    "notifications.community.desc": "News and community features",
    "notifications.updates.title": "App updates",
    "notifications.updates.desc": "New features and improvements",
    
    // Privacy Settings
    "privacy.profile.title": "Profile visibility",
    "privacy.profile.desc": "Show your profile to other users",
    "privacy.location.title": "Location sharing",
    "privacy.location.desc": "Allow location sharing during walks",
    "privacy.anonymous.title": "Anonymous reports",
    "privacy.anonymous.desc": "Keep reports completely anonymous",
    "privacy.data.title": "Data collection",
    "privacy.data.desc": "Allow data collection for improvements",
    "privacy.download.button": "Download my data",
    "privacy.download.title": "Data downloaded",
    "privacy.download.desc": "Your data has been downloaded",
    "privacy.delete.button": "Delete account",
    "privacy.delete.confirm": "Are you sure? This cannot be undone.",
    "privacy.delete.title": "Account deleted",
    "privacy.delete.desc": "Your account and all data have been removed",
    
    // BottomNav
    "bottomnav.map": "Map",
    "bottomnav.report": "Report",
    "bottomnav.walk": "Walk",
    "bottomnav.places": "Places",
    "bottomnav.account": "Account",
    
    // Landing additional sections
    "landing.impact.title": "Our Impact",
    "landing.impact.subtitle": "Building a safer Tunisia, one report at a time",
    "landing.impact.desc": "Since our launch, thousands of women have used EnaZeda to report incidents, find safe routes, and connect with their community. Together, we're creating real change.",
    "landing.testimonials.title": "What Women Say",
    "landing.testimonials.subtitle": "Stories from our community",
    "landing.testimonials.testimonial1": "EnaZeda helped me find safer routes to work. The heatmap is incredibly useful.",
    "landing.testimonials.testimonial2": "I feel safer knowing I can report incidents anonymously and help others.",
    "landing.testimonials.testimonial3": "The Walk With Me feature gives me peace of mind when walking alone.",
    "landing.faq.title": "Frequently Asked Questions",
    "landing.faq.subtitle": "Everything you need to know",
    "landing.faq.q1": "Is my information private?",
    "landing.faq.a1": "Yes, all reports are completely anonymous. We never share your personal information.",
    "landing.faq.q2": "How do I report an incident?",
    "landing.faq.a2": "Simply click the Report button, select the incident type, and submit. It takes less than a minute.",
    "landing.faq.q3": "Are safe spaces verified?",
    "landing.faq.a3": "Yes, all safe spaces are verified by our community before being added to the map.",
    
    // SafetyMap
    "map.title": "Safety Map",
    "map.location": "Tunis",
    "map.safetymap": "Safety map",
    "map.safeplaces": "Safe places",
    "map.risklevel": "Risk level",
    "map.high": "High",
    "map.medium": "Medium",
    "map.safespace": "Safe space",
    
    // ReportIncident
    "report.title": "Report",
    "report.what": "What happened?",
    "report.verbal": "Verbal",
    "report.verbal.desc": "Catcalling, insults, threats",
    "report.physical": "Physical",
    "report.physical.desc": "Touching, grabbing, blocking",
    "report.stalking": "Stalking",
    "report.stalking.desc": "Following, watching",
    "report.assault": "Assault",
    "report.assault.desc": "Physical attack or attempt",
    "report.location": "Location",
    "report.using": "Using current location",
    "report.time": "Time",
    "report.details": "Details (optional)",
    "report.placeholder": "Describe what happened...",
    "report.submit": "Submit report",
    "report.submitting": "Submitting...",
    "report.submitted": "Report submitted",
    "report.thankyou": "Thank you",
    "report.thankyou.desc": "Your report helps keep the community safe.",
    "report.another": "Submit another",
    "report.select": "Select incident type",
    "report.select.desc": "Please select what happened.",
    "report.anonymous": "Reports are anonymous and reviewed within 24 hours.",
    
    // WalkWithMe
    "walk.title": "Walk",
    "walk.choose": "Choose how to stay safe",
    "walk.modes.friend": "Walk with a friend",
    "walk.modes.friend.desc": "Share your live location with a trusted contact",
    "walk.modes.guardian": "Walk with a guardian",
    "walk.modes.guardian.desc": "Connect with a verified volunteer",
    "walk.modes.safe_place": "Walk to safe place",
    "walk.modes.safe_place.desc": "Get directions to the nearest verified location",
    "walk.features.title": "Features during walk",
    "walk.features.live_location": "Live location",
    "walk.features.checkin_timer": "Check-in timer",
    "walk.features.panic_button": "Panic button",
    "walk.features.emergency_call": "Emergency call",
    "walk.start": "Start walk",
    "walk.started": "Walk started",
    "walk.started.desc": "Your location is being shared with selected contacts",
    "walk.walking": "Walking",
    "walk.location_active": "Location sharing active",
    "walk.location_sharing": "Sharing location",
    "walk.shared_with": "Shared with",
    "walk.duration": "Duration",
    "walk.checkin.next": "Next check-in",
    "walk.checkin.sent": "Check-in sent",
    "walk.checkin.sent.desc": "Your contacts have been notified",
    "walk.panic.button": "PANIC BUTTON",
    "walk.panic.desc": "Press to alert emergency contacts and call 197",
    "walk.panic.activated": "Emergency alert activated",
    "walk.panic.activated.desc": "Emergency contacts have been notified",
    "walk.emergency.call": "Call Emergency (197)",
    "walk.emergency.calling": "Calling emergency",
    "walk.emergency.calling.desc": "Connecting to emergency services",
    "walk.end": "End walk",
    "walk.ended": "Walk ended",
    "walk.ended.desc": "Location sharing has been stopped",
    "walk.select_contacts": "Select contacts",
    "walk.select_contacts_list": "Select emergency contacts",
    "walk.select_guardians": "Select guardians",
    "walk.no_contacts_available": "No contacts available",
    "walk.add_contacts_first": "Add emergency contacts or guardians in your profile first",
    "walk.no.contacts": "No contacts selected",
    "walk.no.contacts.desc": "Please select at least one contact or guardian",
    "walk.back": "Back",
    
    // SafeSpaces
    "safespaces.title": "Safe spaces",
    "safespaces.verified": "Verified locations nearby",
    "safespaces.current": "Current location",
    "safespaces.change": "Change",
    "safespaces.badge": "Verified",
    "safespaces.verified_badge": "Verified",
    "safespaces.open": "Open",
    "safespaces.closed": "Closed",
    "safespaces.directions": "Directions",
    "safespaces.footer": "All locations are verified by the community.",
    
    // NotFound
    "notfound.title": "404",
    "notfound.message": "Oops! Page not found",
    "notfound.home": "Return to Home",
  },
  fr: {
    "nav.map": "Carte",
    "nav.report": "Signaler",
    "nav.signin": "Se connecter",
    "nav.signout": "Se déconnecter",
    "nav.getstarted": "Commencer",
    "nav.profile": "Profil",
    "landing.hero.title": "Plateforme de Sécurité pour les Femmes en Tunisie",
    "landing.hero.subtitle": "Signalez le harcèlement de rue, visualisez les zones dangereuses, marchez en toute sécurité avec le soutien de la communauté et accédez à des espaces sûrs vérifiés.",
    "landing.hero.badge": "Plateforme de Sécurité pour les Femmes en Tunisie",
    "landing.hero.map": "Ouvrir la Carte de Sécurité",
    "landing.hero.getstarted": "Commencer",
    "landing.movement.title": "Construire une Tunisie Plus Sûre",
    "landing.movement.description": "EnaZeda représente une position collective contre le harcèlement sexuel en Tunisie. Nous construisons une plateforme communautaire qui permet aux femmes de signaler des incidents, partager des expériences et créer ensemble des espaces publics plus sûrs.",
    "landing.movement.data": "Données en Temps Réel",
    "landing.movement.data.desc": "Visualisez les modèles de harcèlement dans les villes tunisiennes avec notre carte de sécurité interactive.",
    "landing.movement.community": "Soutien Communautaire",
    "landing.movement.community.desc": "Connectez-vous avec des contacts de confiance et des bénévoles vérifiés qui peuvent vous aider à marcher en toute sécurité.",
    "landing.movement.spaces": "Espaces Sûrs Vérifiés",
    "landing.movement.spaces.desc": "Trouvez des cafés, pharmacies et bâtiments publics vérifiés par la communauté comme refuges sûrs.",
    "landing.movement.secure": "Sécurisé et Fiable",
    "landing.movement.secure.desc": "Comptes réels, signalements fiables et infrastructure sécurisée pour votre sécurité et votre vie privée.",
    "landing.howitworks.title": "Comment Ça Marche",
    "landing.howitworks.subtitle": "Une plateforme mobile-first optimisée pour une faible utilisation de données, des performances rapides et l'accessibilité.",
    "landing.howitworks.report": "Signaler des Incidents",
    "landing.howitworks.report.desc": "Signalez anonymement les incidents de harcèlement de rue. Vos signalements aident à construire une carte de sécurité complète pour tous.",
    "landing.howitworks.visualize": "Visualiser les Zones Dangereuses",
    "landing.howitworks.visualize.desc": "Consultez les cartes de chaleur en temps réel des incidents signalés. Planifiez des itinéraires plus sûrs et évitez les zones à haut risque.",
    "landing.howitworks.walk": "Marcher en Toute Sécurité",
    "landing.howitworks.walk.desc": "Partagez votre localisation en direct avec des contacts de confiance. Bouton de panique en un clic pour les urgences.",
    "landing.stats.anonymous": "Signalement Anonyme",
    "landing.stats.support": "Soutien Communautaire",
    "landing.stats.verified": "Espaces Sûrs Vérifiés",
    "landing.cta.title": "Rejoignez le Mouvement",
    "landing.cta.description": "Chaque signalement aide. Chaque marche sûre compte. Ensemble, nous construisons une Tunisie plus sûre pour toutes les femmes.",
    "landing.cta.create": "Créer un Compte",
    "landing.cta.explore": "Explorer la Carte",
    "footer.tagline": "Plateforme de sécurité pour les femmes en Tunisie • Construction d'un réseau de sécurité publique évolutif",
    "footer.about": "À propos",
    "footer.contact": "Contact",
    "footer.privacy": "Politique de Confidentialité",
    "footer.terms": "Conditions d'Utilisation",
    "footer.resources": "Ressources",
    "footer.safetymap": "Carte de Sécurité",
    "footer.report": "Signaler un Incident",
    "footer.safespaces": "Espaces Sûrs",
    "about.title": "À propos d'EnaZeda",
    "about.mission": "Notre Mission",
    "about.mission.desc": "EnaZeda est une plateforme de sécurité conçue spécifiquement pour les femmes en Tunisie. Nous fournissons des outils pour signaler le harcèlement de rue, visualiser les zones dangereuses, marcher en toute sécurité avec le soutien de la communauté et accéder à des espaces sûrs vérifiés.",
    "about.movement": "Le Mouvement",
    "about.movement.desc": "EnaZeda est une plateforme de sécurité qui autonomise les femmes en Tunisie. Nous croyons que chaque femme a le droit de se déplacer librement et en toute sécurité dans les espaces publics.",
    "about.how": "Comment Nous Travaillons",
    "about.anonymous": "Signalement Anonyme",
    "about.anonymous.desc": "Les utilisateurs peuvent signaler anonymement les incidents de harcèlement de rue.",
    "about.verification": "Vérification Communautaire",
    "about.verification.desc": "Les espaces sûrs sont vérifiés par la communauté.",
    "about.support": "Soutien en Temps Réel",
    "about.support.desc": "La fonctionnalité Walk With Me permet aux utilisateurs de partager leur localisation en direct.",
    "about.privacy": "Confidentialité et Sécurité",
    "about.privacy.desc": "Nous prenons la confidentialité et la sécurité au sérieux.",
    "about.involved": "Participer",
    "about.involved.desc": "Rejoignez-nous pour construire une Tunisie plus sûre.",
    "about.create": "Créer un Compte",
    "contact.title": "Contactez-nous",
    "contact.subtitle": "Des questions ou des commentaires? Nous aimerions avoir de vos nouvelles.",
    "contact.name": "Nom",
    "contact.email": "Email",
    "contact.subject": "Sujet",
    "contact.message": "Message",
    "contact.send": "Envoyer le Message",
    "contact.sending": "Envoi...",
    "contact.other": "Autres Moyens de Nous Contacter",
    "contact.email.label": "Email:",
    "contact.support.label": "Support:",
    "privacy.title": "Politique de Confidentialité",
    "privacy.lastupdated": "Dernière mise à jour:",
    "privacy.intro": "Introduction",
    "privacy.intro.desc": "EnaZeda s'engage à protéger votre vie privée.",
    "privacy.collect": "Informations que Nous Collectons",
    "privacy.account": "Informations de Compte",
    "privacy.account.desc": "Lorsque vous créez un compte, nous collectons votre numéro de téléphone.",
    "privacy.reports": "Rapports d'Incidents",
    "privacy.reports.desc": "Les rapports soumis via notre plateforme sont anonymes.",
    "privacy.location": "Données de Localisation",
    "privacy.location.desc": "Les données de localisation sont collectées uniquement lorsque vous utilisez activement certaines fonctionnalités.",
    "privacy.use": "Comment Nous Utilisons Vos Informations",
    "privacy.use.list1": "Pour fournir et maintenir notre plateforme de sécurité",
    "privacy.use.list2": "Pour traiter et afficher les rapports d'incidents anonymes",
    "privacy.use.list3": "Pour activer les fonctionnalités de partage de localisation",
    "privacy.use.list4": "Pour améliorer nos services",
    "privacy.use.list5": "Pour communiquer avec vous",
    "privacy.security": "Sécurité des Données",
    "privacy.security.desc": "Nous mettons en œuvre des mesures techniques et organisationnelles appropriées.",
    "privacy.rights": "Vos Droits",
    "privacy.rights.desc": "Vous avez le droit de:",
    "privacy.rights.list1": "Accéder à vos informations personnelles",
    "privacy.rights.list2": "Demander la correction de données inexactes",
    "privacy.rights.list3": "Demander la suppression de votre compte",
    "privacy.rights.list4": "Vous désinscrire du suivi de localisation",
    "privacy.contact": "Contactez-nous",
    "privacy.contact.desc": "Pour toute question sur cette Politique de Confidentialité, contactez-nous à privacy@enazeda.tn",
    "terms.title": "Conditions d'Utilisation",
    "terms.lastupdated": "Dernière mise à jour:",
    "terms.agreement": "Accord aux Conditions",
    "terms.agreement.desc": "En accédant ou en utilisant EnaZeda, vous acceptez d'être lié par ces Conditions d'Utilisation.",
    "terms.use": "Utilisation du Service",
    "terms.eligibility": "Éligibilité",
    "terms.eligibility.desc": "Vous devez avoir au moins 18 ans pour utiliser EnaZeda.",
    "terms.responsibility": "Responsabilité du Compte",
    "terms.responsibility.desc": "Vous êtes responsable de maintenir la confidentialité de vos identifiants de compte.",
    "terms.acceptable": "Utilisation Acceptable",
    "terms.acceptable.desc": "Vous acceptez d'utiliser EnaZeda uniquement à des fins légales.",
    "terms.reports": "Rapports d'Incidents",
    "terms.reports.desc": "Lors de la soumission de rapports d'incidents, vous acceptez que:",
    "terms.reports.list1": "Les rapports sont soumis de bonne foi",
    "terms.reports.list2": "Vous ne soumettrez pas de rapports faux ou malveillants",
    "terms.reports.list3": "Tous les rapports sont anonymes",
    "terms.reports.list4": "Les rapports peuvent être examinés par notre équipe",
    "terms.liability": "Limitation de Responsabilité",
    "terms.liability.desc": "EnaZeda est fourni \"tel quel\" sans garanties d'aucune sorte.",
    "terms.modifications": "Modifications",
    "terms.modifications.desc": "Nous nous réservons le droit de modifier ces Conditions à tout moment.",
    "terms.contact": "Contact",
    "terms.contact.desc": "Pour toute question sur ces Conditions, contactez-nous à legal@enazeda.tn",
    "auth.welcome": "Bienvenue sur EnaZeda",
    "auth.subtitle": "Connectez-vous pour accéder à la plateforme de sécurité",
    "auth.phone": "Numéro de Téléphone",
    "auth.email": "Email",
    "auth.email.placeholder": "votre@email.com",
    "auth.password": "Mot de passe",
    "auth.password.placeholder": "Entrez votre mot de passe",
    "auth.signin": "Se connecter",
    "auth.signup": "S'inscrire",
    "auth.or": "Ou",
    "auth.google": "Continuer avec Google",
    "auth.phone.option": "Utiliser le téléphone à la place",
    "auth.switch": "Passer à l'email",
    "auth.continue": "Continuer",
    "auth.sending": "Envoi du code...",
    "auth.verify": "Vérifiez votre numéro",
    "auth.sent": "Nous avons envoyé un code à",
    "auth.verifybutton": "Vérifier et Se Connecter",
    "auth.verifying": "Vérification...",
    "auth.change": "Changer le numéro",
    "auth.noaccount": "Vous n'avez pas de compte?",
    "auth.haveaccount": "Vous avez déjà un compte?",
    "auth.forgot": "Mot de passe oublié?",
    "auth.agree": "En continuant, vous acceptez nos conditions d'utilisation et notre politique de confidentialité.",
    "profile.title": "Compte",
    "profile.notsigned": "Non connecté",
    "profile.signin": "Se connecter",
    "profile.trust": "Score de confiance",
    "profile.trust.desc": "Construisez la confiance en contribuant à la communauté.",
    "profile.contacts": "Contacts d'urgence",
    "profile.contacts.desc": "Gérer les contacts de confiance",
    "profile.guardians": "Gardiens de confiance",
    "profile.guardians.desc": "Personnes qui peuvent rejoindre les promenades",
    "profile.history": "Historique",
    "profile.history.desc": "Rapports et promenades passés",
    "profile.notifications": "Notifications",
    "profile.notifications.desc": "Préférences d'alerte",
    "profile.language": "Langue",
    "profile.language.desc": "Français",
    "profile.privacy": "Confidentialité",
    "profile.privacy.desc": "Contrôlez vos données",
    "profile.signout": "Se déconnecter",
    
    // Emergency Contacts
    "contacts.add": "Ajouter un contact",
    "contacts.save": "Enregistrer",
    "contacts.update": "Mettre à jour",
    "contacts.cancel": "Annuler",
    "contacts.form.name": "Nom",
    "contacts.form.name.placeholder": "Nom du contact",
    "contacts.form.phone": "Téléphone",
    "contacts.form.phone.placeholder": "+216 XX XXX XXX",
    "contacts.error.title": "Informations manquantes",
    "contacts.error.desc": "Veuillez remplir tous les champs requis",
    "contacts.added.title": "Contact ajouté",
    "contacts.added.desc": "Le contact d'urgence a été enregistré",
    "contacts.updated.title": "Contact mis à jour",
    "contacts.updated.desc": "Le contact d'urgence a été mis à jour",
    "contacts.deleted.title": "Contact supprimé",
    "contacts.deleted.desc": "Le contact d'urgence a été supprimé",
    "contacts.empty.title": "Aucun contact d'urgence",
    "contacts.empty.desc": "Ajoutez des contacts de confiance pour les situations d'urgence",
    
    // Trusted Guardians
    "guardians.add": "Ajouter un gardien",
    "guardians.save": "Enregistrer",
    "guardians.update": "Mettre à jour",
    "guardians.cancel": "Annuler",
    "guardians.form.name": "Nom",
    "guardians.form.name.placeholder": "Nom du gardien",
    "guardians.form.phone": "Téléphone",
    "guardians.form.phone.placeholder": "+216 XX XXX XXX",
    "guardians.form.email": "Email",
    "guardians.form.email.optional": "Optionnel",
    "guardians.form.email.placeholder": "gardien@email.com",
    "guardians.error.title": "Informations manquantes",
    "guardians.error.desc": "Veuillez remplir le nom et le téléphone",
    "guardians.added.title": "Gardien ajouté",
    "guardians.added.desc": "Le gardien de confiance a été enregistré",
    "guardians.updated.title": "Gardien mis à jour",
    "guardians.updated.desc": "Le gardien de confiance a été mis à jour",
    "guardians.deleted.title": "Gardien supprimé",
    "guardians.deleted.desc": "Le gardien de confiance a été supprimé",
    "guardians.empty.title": "Aucun gardien de confiance",
    "guardians.empty.desc": "Ajoutez des personnes qui peuvent rejoindre vos promenades",
    
    // History
    "history.filter.all": "Tout",
    "history.filter.reports": "Rapports",
    "history.filter.walks": "Promenades",
    "history.empty.title": "Aucun historique",
    "history.empty.desc": "Vos rapports et promenades apparaîtront ici",
    
    // Notifications
    "notifications.reports.title": "Notifications de rapports",
    "notifications.reports.desc": "Recevoir des notifications sur les incidents à proximité",
    "notifications.walks.title": "Notifications de promenades",
    "notifications.walks.desc": "Alertes pendant les sessions de marche",
    "notifications.safeSpaces.title": "Espaces sûrs",
    "notifications.safeSpaces.desc": "Mises à jour sur les emplacements sûrs vérifiés",
    "notifications.emergency.title": "Alertes d'urgence",
    "notifications.emergency.desc": "Notifications de sécurité critiques",
    "notifications.community.title": "Mises à jour communautaires",
    "notifications.community.desc": "Actualités et fonctionnalités communautaires",
    "notifications.updates.title": "Mises à jour de l'application",
    "notifications.updates.desc": "Nouvelles fonctionnalités et améliorations",
    
    // Privacy Settings
    "privacy.profile.title": "Visibilité du profil",
    "privacy.profile.desc": "Afficher votre profil aux autres utilisateurs",
    "privacy.location.title": "Partage de localisation",
    "privacy.location.desc": "Autoriser le partage de localisation pendant les promenades",
    "privacy.anonymous.title": "Rapports anonymes",
    "privacy.anonymous.desc": "Garder les rapports complètement anonymes",
    "privacy.data.title": "Collecte de données",
    "privacy.data.desc": "Autoriser la collecte de données pour les améliorations",
    "privacy.download.button": "Télécharger mes données",
    "privacy.download.title": "Données téléchargées",
    "privacy.download.desc": "Vos données ont été téléchargées",
    "privacy.delete.button": "Supprimer le compte",
    "privacy.delete.confirm": "Êtes-vous sûr? Cette action est irréversible.",
    "privacy.delete.title": "Compte supprimé",
    "privacy.delete.desc": "Votre compte et toutes les données ont été supprimés",
    
    "bottomnav.map": "Carte",
    "bottomnav.report": "Signaler",
    "bottomnav.walk": "Marcher",
    "bottomnav.places": "Lieux",
    "bottomnav.account": "Compte",
    "landing.impact.title": "Notre Impact",
    "landing.impact.subtitle": "Construire une Tunisie plus sûre, un rapport à la fois",
    "landing.impact.desc": "Depuis notre lancement, des milliers de femmes ont utilisé EnaZeda pour signaler des incidents, trouver des itinéraires sûrs et se connecter avec leur communauté.",
    "landing.testimonials.title": "Ce que Disent les Femmes",
    "landing.testimonials.subtitle": "Témoignages de notre communauté",
    "landing.testimonials.testimonial1": "EnaZeda m'a aidé à trouver des itinéraires plus sûrs pour aller au travail.",
    "landing.testimonials.testimonial2": "Je me sens plus en sécurité en sachant que je peux signaler des incidents anonymement.",
    "landing.testimonials.testimonial3": "La fonctionnalité Walk With Me me donne la tranquillité d'esprit.",
    "landing.faq.title": "Questions Fréquemment Posées",
    "landing.faq.subtitle": "Tout ce que vous devez savoir",
    "landing.faq.q1": "Mes informations sont-elles privées?",
    "landing.faq.a1": "Oui, tous les rapports sont complètement anonymes.",
    "landing.faq.q2": "Comment signaler un incident?",
    "landing.faq.a2": "Cliquez simplement sur le bouton Signaler, sélectionnez le type d'incident et soumettez.",
    "landing.faq.a3": "Oui, tous les espaces sûrs sont vérifiés par notre communauté.",
    "map.title": "Carte de Sécurité",
    "map.location": "Tunis",
    "map.safetymap": "Carte de sécurité",
    "map.safeplaces": "Espaces sûrs",
    "map.risklevel": "Niveau de risque",
    "map.high": "Élevé",
    "map.medium": "Moyen",
    "map.safespace": "Espace sûr",
    "report.title": "Signaler",
    "report.what": "Que s'est-il passé?",
    "report.verbal": "Verbal",
    "report.verbal.desc": "Sifflements, insultes, menaces",
    "report.physical": "Physique",
    "report.physical.desc": "Toucher, saisir, bloquer",
    "report.stalking": "Harcèlement",
    "report.stalking.desc": "Suivre, surveiller",
    "report.assault": "Agression",
    "report.assault.desc": "Attaque physique ou tentative",
    "report.location": "Localisation",
    "report.using": "Utiliser la localisation actuelle",
    "report.time": "Heure",
    "report.details": "Détails (optionnel)",
    "report.placeholder": "Décrivez ce qui s'est passé...",
    "report.submit": "Soumettre le rapport",
    "report.submitting": "Soumission...",
    "report.submitted": "Rapport soumis",
    "report.thankyou": "Merci",
    "report.thankyou.desc": "Votre rapport aide à garder la communauté en sécurité.",
    "report.another": "Soumettre un autre",
    "report.select": "Sélectionner le type d'incident",
    "report.select.desc": "Veuillez sélectionner ce qui s'est passé.",
    "report.anonymous": "Les rapports sont anonymes et examinés dans les 24 heures.",
    "walk.title": "Marcher",
    "walk.choose": "Choisissez comment rester en sécurité",
    "walk.modes.friend": "Marcher avec un ami",
    "walk.modes.friend.desc": "Partagez votre localisation en direct avec un contact de confiance",
    "walk.modes.guardian": "Marcher avec un gardien",
    "walk.modes.guardian.desc": "Connectez-vous avec un bénévole vérifié",
    "walk.modes.safe_place": "Marcher vers un lieu sûr",
    "walk.modes.safe_place.desc": "Obtenez des directions vers le lieu vérifié le plus proche",
    "walk.features.title": "Fonctionnalités pendant la marche",
    "walk.features.live_location": "Localisation en direct",
    "walk.features.checkin_timer": "Minuteur de vérification",
    "walk.features.panic_button": "Bouton de panique",
    "walk.features.emergency_call": "Appel d'urgence",
    "walk.start": "Commencer la marche",
    "walk.started": "Marche commencée",
    "walk.started.desc": "Votre localisation est partagée avec les contacts sélectionnés",
    "walk.walking": "En marche",
    "walk.location_active": "Partage de localisation actif",
    "walk.location_sharing": "Partage de localisation",
    "walk.shared_with": "Partagé avec",
    "walk.duration": "Durée",
    "walk.checkin.next": "Prochaine vérification",
    "walk.checkin.sent": "Vérification envoyée",
    "walk.checkin.sent.desc": "Vos contacts ont été notifiés",
    "walk.panic.button": "BOUTON DE PANIQUE",
    "walk.panic.desc": "Appuyez pour alerter les contacts d'urgence et appeler le 197",
    "walk.panic.activated": "Alerte d'urgence activée",
    "walk.panic.activated.desc": "Les contacts d'urgence ont été notifiés",
    "walk.emergency.call": "Appeler les urgences (197)",
    "walk.emergency.calling": "Appel des urgences",
    "walk.emergency.calling.desc": "Connexion aux services d'urgence",
    "walk.end": "Terminer la marche",
    "walk.ended": "Marche terminée",
    "walk.ended.desc": "Le partage de localisation a été arrêté",
    "walk.select_contacts": "Sélectionner les contacts",
    "walk.select_contacts_list": "Sélectionner les contacts d'urgence",
    "walk.select_guardians": "Sélectionner les gardiens",
    "walk.no_contacts_available": "Aucun contact disponible",
    "walk.add_contacts_first": "Ajoutez d'abord des contacts d'urgence ou des gardiens dans votre profil",
    "walk.no.contacts": "Aucun contact sélectionné",
    "walk.no.contacts.desc": "Veuillez sélectionner au moins un contact ou gardien",
    "walk.back": "Retour",
    "safespaces.title": "Espaces sûrs",
    "safespaces.verified": "Lieux vérifiés à proximité",
    "safespaces.current": "Localisation actuelle",
    "safespaces.change": "Changer",
    "safespaces.badge": "Vérifié",
    "safespaces.verified_badge": "Vérifié",
    "safespaces.open": "Ouvert",
    "safespaces.closed": "Fermé",
    "safespaces.directions": "Itinéraire",
    "safespaces.footer": "Tous les lieux sont vérifiés par la communauté.",
    "notfound.title": "404",
    "notfound.message": "Oups! Page non trouvée",
    "notfound.home": "Retour à l'accueil",
  },
  ar: {
    "nav.map": "الخريطة",
    "nav.report": "الإبلاغ",
    "nav.signin": "تسجيل الدخول",
    "nav.signout": "تسجيل الخروج",
    "nav.getstarted": "ابدأ",
    "nav.profile": "الملف الشخصي",
    "landing.hero.title": "منصة السلامة للنساء في تونس",
    "landing.hero.subtitle": "أبلغ عن التحرش في الشارع، تصور المناطق الخطرة، امش بأمان بدعم المجتمع واحصل على مساحات آمنة موثقة.",
    "landing.hero.badge": "منصة السلامة للنساء في تونس",
    "landing.hero.map": "افتح خريطة السلامة",
    "landing.hero.getstarted": "ابدأ",
    "landing.movement.title": "بناء تونس أكثر أماناً",
    "landing.movement.description": "أنا زادة تمثل موقفاً جماعياً ضد التحرش الجنسي في تونس. نبني منصة قائمة على المجتمع تمكن النساء من الإبلاغ عن الحوادث ومشاركة التجارب وخلق مساحات عامة أكثر أماناً معاً.",
    "landing.movement.data": "البيانات في الوقت الفعلي",
    "landing.movement.data.desc": "تصور أنماط التحرش عبر المدن التونسية مع خريطة السلامة التفاعلية الخاصة بنا.",
    "landing.movement.community": "الدعم المجتمعي",
    "landing.movement.community.desc": "تواصل مع جهات اتصال موثوقة ومتطوعين موثقين يمكنهم مساعدتك على المشي بأمان.",
    "landing.movement.spaces": "مساحات آمنة موثقة",
    "landing.movement.spaces.desc": "ابحث عن المقاهي والصيدليات والمباني العامة التي تم التحقق منها من قبل المجتمع كملاذات آمنة.",
    "landing.movement.secure": "آمن وموثوق",
    "landing.movement.secure.desc": "حسابات حقيقية وإبلاغات موثوقة وبنية تحتية آمنة لسلامتك وخصوصيتك.",
    "landing.howitworks.title": "كيف يعمل",
    "landing.howitworks.subtitle": "منصة موجهة للهاتف المحمول محسّنة لاستخدام بيانات منخفض وأداء سريع وإمكانية الوصول.",
    "landing.howitworks.report": "الإبلاغ عن الحوادث",
    "landing.howitworks.report.desc": "أبلغ عن حوادث التحرش في الشارع بشكل مجهول. تساعد تقاريرك في بناء خريطة سلامة شاملة للجميع.",
    "landing.howitworks.visualize": "تصور المناطق الخطرة",
    "landing.howitworks.visualize.desc": "شاهد خرائط الحرارة في الوقت الفعلي للحوادث المبلغ عنها. خطط لطرق أكثر أماناً وتجنب المناطق عالية المخاطر.",
    "landing.howitworks.walk": "امش بأمان",
    "landing.howitworks.walk.desc": "شارك موقعك المباشر مع جهات اتصال موثوقة. زر الذعر بنقرة واحدة للطوارئ.",
    "landing.stats.anonymous": "الإبلاغ المجهول",
    "landing.stats.support": "الدعم المجتمعي",
    "landing.stats.verified": "مساحات آمنة موثقة",
    "landing.cta.title": "انضم إلى الحركة",
    "landing.cta.description": "كل تقرير يساعد. كل مشي آمن مهم. معاً، نبني تونساً أكثر أماناً لجميع النساء.",
    "landing.cta.create": "إنشاء حساب",
    "landing.cta.explore": "استكشف الخريطة",
    "footer.tagline": "منصة السلامة للنساء في تونس • بناء شبكة سلامة عامة قابلة للتوسع",
    "footer.about": "حول",
    "footer.contact": "اتصل بنا",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.resources": "الموارد",
    "footer.safetymap": "خريطة السلامة",
    "footer.report": "الإبلاغ عن حادث",
    "footer.safespaces": "المساحات الآمنة",
    "about.title": "حول أنا زادة",
    "about.mission": "مهمتنا",
    "about.mission.desc": "أنا زادة هي منصة سلامة مصممة خصيصاً للنساء في تونس.",
    "about.movement": "الحركة",
    "about.movement.desc": "أنا زادة هي منصة سلامة تمكن النساء في تونس. نؤمن بأن لكل امرأة الحق في التنقل بحرية وأمان في الأماكن العامة.",
    "about.how": "كيف نعمل",
    "about.anonymous": "الإبلاغ المجهول",
    "about.anonymous.desc": "يمكن للمستخدمين الإبلاغ بشكل مجهول عن حوادث التحرش في الشارع.",
    "about.verification": "التحقق المجتمعي",
    "about.verification.desc": "يتم التحقق من المساحات الآمنة من قبل المجتمع.",
    "about.support": "الدعم في الوقت الفعلي",
    "about.support.desc": "تسمح ميزة امش معي للمستخدمين بمشاركة موقعهم المباشر.",
    "about.privacy": "الخصوصية والأمان",
    "about.privacy.desc": "نأخذ الخصوصية والأمان على محمل الجد.",
    "about.involved": "المشاركة",
    "about.involved.desc": "انضم إلينا لبناء تونس أكثر أماناً.",
    "about.create": "إنشاء حساب",
    "contact.title": "اتصل بنا",
    "contact.subtitle": "لديك أسئلة أو ملاحظات؟ نحب أن نسمع منك.",
    "contact.name": "الاسم",
    "contact.email": "البريد الإلكتروني",
    "contact.subject": "الموضوع",
    "contact.message": "الرسالة",
    "contact.send": "إرسال الرسالة",
    "contact.sending": "جاري الإرسال...",
    "contact.other": "طرق أخرى للتواصل معنا",
    "contact.email.label": "البريد الإلكتروني:",
    "contact.support.label": "الدعم:",
    "privacy.title": "سياسة الخصوصية",
    "privacy.lastupdated": "آخر تحديث:",
    "privacy.intro": "مقدمة",
    "privacy.intro.desc": "أنا زادة ملتزمة بحماية خصوصيتك.",
    "privacy.collect": "المعلومات التي نجمعها",
    "privacy.account": "معلومات الحساب",
    "privacy.account.desc": "عند إنشاء حساب، نجمع رقم هاتفك.",
    "privacy.reports": "تقارير الحوادث",
    "privacy.reports.desc": "التقارير المقدمة عبر منصتنا مجهولة.",
    "privacy.location": "بيانات الموقع",
    "privacy.location.desc": "يتم جمع بيانات الموقع فقط عند استخدامك النشط لبعض الميزات.",
    "privacy.use": "كيف نستخدم معلوماتك",
    "privacy.use.list1": "لتوفير وصيانة منصة السلامة الخاصة بنا",
    "privacy.use.list2": "لمعالجة وعرض تقارير الحوادث المجهولة",
    "privacy.use.list3": "لتفعيل ميزات مشاركة الموقع",
    "privacy.use.list4": "لتحسين خدماتنا",
    "privacy.use.list5": "للتواصل معك",
    "privacy.security": "أمان البيانات",
    "privacy.security.desc": "ننفذ تدابير تقنية وتنظيمية مناسبة.",
    "privacy.rights": "حقوقك",
    "privacy.rights.desc": "لديك الحق في:",
    "privacy.rights.list1": "الوصول إلى معلوماتك الشخصية",
    "privacy.rights.list2": "طلب تصحيح البيانات غير الدقيقة",
    "privacy.rights.list3": "طلب حذف حسابك",
    "privacy.rights.list4": "إلغاء الاشتراك في تتبع الموقع",
    "privacy.contact": "اتصل بنا",
    "privacy.contact.desc": "لأي أسئلة حول سياسة الخصوصية هذه، اتصل بنا على privacy@enazeda.tn",
    "terms.title": "شروط الخدمة",
    "terms.lastupdated": "آخر تحديث:",
    "terms.agreement": "الموافقة على الشروط",
    "terms.agreement.desc": "من خلال الوصول إلى أو استخدام أنا زادة، أنت توافق على الالتزام بشروط الخدمة هذه.",
    "terms.use": "استخدام الخدمة",
    "terms.eligibility": "الأهلية",
    "terms.eligibility.desc": "يجب أن يكون عمرك 18 عاماً على الأقل لاستخدام أنا زادة.",
    "terms.responsibility": "مسؤولية الحساب",
    "terms.responsibility.desc": "أنت مسؤول عن الحفاظ على سرية بيانات اعتماد حسابك.",
    "terms.acceptable": "الاستخدام المقبول",
    "terms.acceptable.desc": "أنت توافق على استخدام أنا زادة فقط للأغراض القانونية.",
    "terms.reports": "تقارير الحوادث",
    "terms.reports.desc": "عند تقديم تقارير الحوادث، أنت توافق على أن:",
    "terms.reports.list1": "يتم تقديم التقارير بحسن نية",
    "terms.reports.list2": "لن تقدم تقارير كاذبة أو خبيثة",
    "terms.reports.list3": "جميع التقارير مجهولة",
    "terms.reports.list4": "قد يتم مراجعة التقارير من قبل فريقنا",
    "terms.liability": "تحديد المسؤولية",
    "terms.liability.desc": "يتم توفير أنا زادة \"كما هو\" دون ضمانات من أي نوع.",
    "terms.modifications": "التعديلات",
    "terms.modifications.desc": "نحتفظ بالحق في تعديل هذه الشروط في أي وقت.",
    "terms.contact": "اتصل بنا",
    "terms.contact.desc": "لأي أسئلة حول هذه الشروط، اتصل بنا على legal@enazeda.tn",
    "auth.welcome": "مرحباً بك في أنا زادة",
    "auth.subtitle": "قم بتسجيل الدخول للوصول إلى منصة السلامة",
    "auth.email": "البريد الإلكتروني",
    "auth.email.placeholder": "your@email.com",
    "auth.password": "كلمة المرور",
    "auth.password.placeholder": "أدخل كلمة المرور",
    "auth.signin": "تسجيل الدخول",
    "auth.signup": "إنشاء حساب",
    "auth.or": "أو",
    "auth.google": "المتابعة مع Google",
    "auth.phone": "رقم الهاتف",
    "auth.phone.option": "استخدام الهاتف بدلاً من ذلك",
    "auth.switch": "التبديل إلى البريد الإلكتروني",
    "auth.continue": "متابعة",
    "auth.sending": "جاري إرسال الرمز...",
    "auth.verify": "تحقق من رقمك",
    "auth.sent": "أرسلنا رمزاً إلى",
    "auth.verifybutton": "تحقق وتسجيل الدخول",
    "auth.verifying": "جاري التحقق...",
    "auth.change": "تغيير الرقم",
    "auth.noaccount": "ليس لديك حساب؟",
    "auth.haveaccount": "لديك حساب بالفعل؟",
    "auth.forgot": "نسيت كلمة المرور؟",
    "auth.agree": "بالمتابعة، أنت توافق على شروط الخدمة وسياسة الخصوصية الخاصة بنا.",
    "profile.title": "الحساب",
    "profile.notsigned": "غير مسجل الدخول",
    "profile.signin": "تسجيل الدخول",
    "profile.trust": "نقاط الثقة",
    "profile.trust.desc": "ابني الثقة من خلال المساهمة في المجتمع.",
    "profile.contacts": "جهات الاتصال الطارئة",
    "profile.contacts.desc": "إدارة جهات الاتصال الموثوقة",
    "profile.guardians": "الأوصياء الموثوقون",
    "profile.guardians.desc": "الأشخاص الذين يمكنهم الانضمام إلى المشي",
    "profile.history": "السجل",
    "profile.history.desc": "التقارير والمشي السابقة",
    "profile.notifications": "الإشعارات",
    "profile.notifications.desc": "تفضيلات التنبيه",
    "profile.language": "اللغة",
    "profile.language.desc": "العربية",
    "profile.privacy": "الخصوصية",
    "profile.privacy.desc": "التحكم في بياناتك",
    "profile.signout": "تسجيل الخروج",
    
    // Emergency Contacts
    "contacts.add": "إضافة جهة اتصال",
    "contacts.save": "حفظ",
    "contacts.update": "تحديث",
    "contacts.cancel": "إلغاء",
    "contacts.form.name": "الاسم",
    "contacts.form.name.placeholder": "اسم جهة الاتصال",
    "contacts.form.phone": "الهاتف",
    "contacts.form.phone.placeholder": "+216 XX XXX XXX",
    "contacts.error.title": "معلومات ناقصة",
    "contacts.error.desc": "يرجى ملء جميع الحقول المطلوبة",
    "contacts.added.title": "تمت إضافة جهة الاتصال",
    "contacts.added.desc": "تم حفظ جهة الاتصال الطارئة",
    "contacts.updated.title": "تم تحديث جهة الاتصال",
    "contacts.updated.desc": "تم تحديث جهة الاتصال الطارئة",
    "contacts.deleted.title": "تم حذف جهة الاتصال",
    "contacts.deleted.desc": "تمت إزالة جهة الاتصال الطارئة",
    "contacts.empty.title": "لا توجد جهات اتصال طارئة",
    "contacts.empty.desc": "أضف جهات اتصال موثوقة للحالات الطارئة",
    
    // Trusted Guardians
    "guardians.add": "إضافة وصي",
    "guardians.save": "حفظ",
    "guardians.update": "تحديث",
    "guardians.cancel": "إلغاء",
    "guardians.form.name": "الاسم",
    "guardians.form.name.placeholder": "اسم الوصي",
    "guardians.form.phone": "الهاتف",
    "guardians.form.phone.placeholder": "+216 XX XXX XXX",
    "guardians.form.email": "البريد الإلكتروني",
    "guardians.form.email.optional": "اختياري",
    "guardians.form.email.placeholder": "guardian@email.com",
    "guardians.error.title": "معلومات ناقصة",
    "guardians.error.desc": "يرجى ملء الاسم والهاتف",
    "guardians.added.title": "تمت إضافة الوصي",
    "guardians.added.desc": "تم حفظ الوصي الموثوق",
    "guardians.updated.title": "تم تحديث الوصي",
    "guardians.updated.desc": "تم تحديث الوصي الموثوق",
    "guardians.deleted.title": "تم حذف الوصي",
    "guardians.deleted.desc": "تمت إزالة الوصي الموثوق",
    "guardians.empty.title": "لا يوجد أوصياء موثوقون",
    "guardians.empty.desc": "أضف أشخاصاً يمكنهم الانضمام إلى مشيك",
    
    // History
    "history.filter.all": "الكل",
    "history.filter.reports": "التقارير",
    "history.filter.walks": "المشي",
    "history.empty.title": "لا يوجد سجل",
    "history.empty.desc": "ستظهر تقاريرك ومشيك هنا",
    
    // Notifications
    "notifications.reports.title": "إشعارات التقارير",
    "notifications.reports.desc": "تلقي إشعارات حول الحوادث القريبة",
    "notifications.walks.title": "إشعارات المشي",
    "notifications.walks.desc": "تنبيهات أثناء جلسات المشي",
    "notifications.safeSpaces.title": "المساحات الآمنة",
    "notifications.safeSpaces.desc": "تحديثات حول المواقع الآمنة الموثقة",
    "notifications.emergency.title": "تنبيهات الطوارئ",
    "notifications.emergency.desc": "إشعارات السلامة الحرجة",
    "notifications.community.title": "تحديثات المجتمع",
    "notifications.community.desc": "الأخبار والميزات المجتمعية",
    "notifications.updates.title": "تحديثات التطبيق",
    "notifications.updates.desc": "ميزات وتحسينات جديدة",
    
    // Privacy Settings
    "privacy.profile.title": "رؤية الملف الشخصي",
    "privacy.profile.desc": "عرض ملفك الشخصي للمستخدمين الآخرين",
    "privacy.location.title": "مشاركة الموقع",
    "privacy.location.desc": "السماح بمشاركة الموقع أثناء المشي",
    "privacy.anonymous.title": "تقارير مجهولة",
    "privacy.anonymous.desc": "الحفاظ على التقارير مجهولة تماماً",
    "privacy.data.title": "جمع البيانات",
    "privacy.data.desc": "السماح بجمع البيانات للتحسينات",
    "privacy.download.button": "تنزيل بياناتي",
    "privacy.download.title": "تم تنزيل البيانات",
    "privacy.download.desc": "تم تنزيل بياناتك",
    "privacy.delete.button": "حذف الحساب",
    "privacy.delete.confirm": "هل أنت متأكد؟ لا يمكن التراجع عن هذا.",
    "privacy.delete.title": "تم حذف الحساب",
    "privacy.delete.desc": "تم حذف حسابك وجميع البيانات",
    
    "bottomnav.map": "الخريطة",
    "bottomnav.report": "الإبلاغ",
    "bottomnav.walk": "المشي",
    "bottomnav.places": "الأماكن",
    "bottomnav.account": "الحساب",
    "landing.impact.title": "تأثيرنا",
    "landing.impact.subtitle": "بناء تونس أكثر أماناً، تقرير واحد في كل مرة",
    "landing.impact.desc": "منذ إطلاقنا، استخدمت آلاف النساء أنا زادة للإبلاغ عن الحوادث والعثور على طرق آمنة.",
    "landing.testimonials.title": "ماذا تقول النساء",
    "landing.testimonials.subtitle": "قصص من مجتمعنا",
    "landing.testimonials.testimonial1": "ساعدتني أنا زادة في العثور على طرق أكثر أماناً للذهاب إلى العمل.",
    "landing.testimonials.testimonial2": "أشعر بأمان أكبر مع العلم أنني أستطيع الإبلاغ عن الحوادث بشكل مجهول.",
    "landing.testimonials.testimonial3": "ميزة امش معي تمنحني راحة البال.",
    "landing.faq.title": "الأسئلة الشائعة",
    "landing.faq.subtitle": "كل ما تحتاج معرفته",
    "landing.faq.q1": "هل معلوماتي خاصة؟",
    "landing.faq.a1": "نعم، جميع التقارير مجهولة تماماً.",
    "landing.faq.q2": "كيف أبلغ عن حادث؟",
    "landing.faq.a2": "ما عليك سوى النقر على زر الإبلاغ واختيار نوع الحادث وإرساله.",
    "landing.faq.q3": "هل المساحات الآمنة موثقة؟",
    "landing.faq.a3": "نعم، يتم التحقق من جميع المساحات الآمنة من قبل مجتمعنا قبل إضافتها إلى الخريطة.",
    "map.title": "خريطة السلامة",
    "map.location": "تونس",
    "map.safetymap": "خريطة السلامة",
    "map.safeplaces": "الأماكن الآمنة",
    "map.risklevel": "مستوى الخطر",
    "map.high": "عالي",
    "map.medium": "متوسط",
    "map.safespace": "مساحة آمنة",
    "report.title": "الإبلاغ",
    "report.what": "ماذا حدث؟",
    "report.verbal": "لفظي",
    "report.verbal.desc": "التحرش اللفظي، الإهانات، التهديدات",
    "report.physical": "جسدي",
    "report.physical.desc": "اللمس، الإمساك، الحجب",
    "report.stalking": "الملاحقة",
    "report.stalking.desc": "المتابعة، المراقبة",
    "report.assault": "اعتداء",
    "report.assault.desc": "هجوم جسدي أو محاولة",
    "report.location": "الموقع",
    "report.using": "استخدام الموقع الحالي",
    "report.time": "الوقت",
    "report.details": "التفاصيل (اختياري)",
    "report.placeholder": "صف ما حدث...",
    "report.submit": "إرسال التقرير",
    "report.submitting": "جاري الإرسال...",
    "report.submitted": "تم إرسال التقرير",
    "report.thankyou": "شكراً لك",
    "report.thankyou.desc": "تقريرك يساعد في الحفاظ على سلامة المجتمع.",
    "report.another": "إرسال آخر",
    "report.select": "اختر نوع الحادث",
    "report.select.desc": "يرجى اختيار ما حدث.",
    "report.anonymous": "التقارير مجهولة ومراجعة خلال 24 ساعة.",
    "walk.title": "المشي",
    "walk.choose": "اختر كيف تبقى آمناً",
    "walk.modes.friend": "امش مع صديق",
    "walk.modes.friend.desc": "شارك موقعك المباشر مع جهة اتصال موثوقة",
    "walk.modes.guardian": "امش مع وصي",
    "walk.modes.guardian.desc": "تواصل مع متطوع موثق",
    "walk.modes.safe_place": "امش إلى مكان آمن",
    "walk.modes.safe_place.desc": "احصل على اتجاهات إلى أقرب موقع موثق",
    "walk.features.title": "الميزات أثناء المشي",
    "walk.features.live_location": "الموقع المباشر",
    "walk.features.checkin_timer": "مؤقت التحقق",
    "walk.features.panic_button": "زر الذعر",
    "walk.features.emergency_call": "اتصال الطوارئ",
    "walk.start": "بدء المشي",
    "walk.started": "بدأ المشي",
    "walk.started.desc": "يتم مشاركة موقعك مع جهات الاتصال المحددة",
    "walk.walking": "المشي",
    "walk.location_active": "مشاركة الموقع نشطة",
    "walk.location_sharing": "مشاركة الموقع",
    "walk.shared_with": "مشارك مع",
    "walk.duration": "المدة",
    "walk.checkin.next": "التحقق التالي",
    "walk.checkin.sent": "تم إرسال التحقق",
    "walk.checkin.sent.desc": "تم إشعار جهات اتصالك",
    "walk.panic.button": "زر الذعر",
    "walk.panic.desc": "اضغط للتنبيه جهات الاتصال الطارئة والاتصال بـ 197",
    "walk.panic.activated": "تم تفعيل تنبيه الطوارئ",
    "walk.panic.activated.desc": "تم إشعار جهات الاتصال الطارئة",
    "walk.emergency.call": "اتصل بالطوارئ (197)",
    "walk.emergency.calling": "جاري الاتصال بالطوارئ",
    "walk.emergency.calling.desc": "الاتصال بخدمات الطوارئ",
    "walk.end": "إنهاء المشي",
    "walk.ended": "انتهى المشي",
    "walk.ended.desc": "تم إيقاف مشاركة الموقع",
    "walk.select_contacts": "اختر جهات الاتصال",
    "walk.select_contacts_list": "اختر جهات الاتصال الطارئة",
    "walk.select_guardians": "اختر الأوصياء",
    "walk.no_contacts_available": "لا توجد جهات اتصال متاحة",
    "walk.add_contacts_first": "أضف جهات اتصال طارئة أو أوصياء في ملفك الشخصي أولاً",
    "walk.no.contacts": "لم يتم اختيار جهات اتصال",
    "walk.no.contacts.desc": "يرجى اختيار جهة اتصال أو وصي واحد على الأقل",
    "walk.back": "رجوع",
    "safespaces.title": "المساحات الآمنة",
    "safespaces.verified": "مواقع موثقة قريبة",
    "safespaces.current": "الموقع الحالي",
    "safespaces.change": "تغيير",
    "safespaces.badge": "موثق",
    "safespaces.verified_badge": "موثق",
    "safespaces.open": "مفتوح",
    "safespaces.closed": "مغلق",
    "safespaces.directions": "الاتجاهات",
    "safespaces.footer": "جميع المواقع موثقة من قبل المجتمع.",
    "notfound.title": "404",
    "notfound.message": "عذراً! الصفحة غير موجودة",
    "notfound.home": "العودة إلى الصفحة الرئيسية",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("enazeda_language") as Language;
    return saved && ["en", "fr", "ar"].includes(saved) ? saved : "en";
  });

  useEffect(() => {
    localStorage.setItem("enazeda_language", language);
    document.documentElement.setAttribute("dir", language === "ar" ? "rtl" : "ltr");
    document.documentElement.setAttribute("lang", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
